/*""FILE COMMENT""*******************************************************
* System Name	: API for RX62T
* File Name		: r_pdl_common_defs_RX62Txx.h
* Version		: 1.01
* Contents		: API common definitions
* Customer		:
* Model			:
* Order			:
* CPU			: RX
* Compiler		: RXC
* OS			: Nothing
* Programmer	:
* Note			:
************************************************************************
* Copyright, 2011. Renesas Electronics Corporation
* and Renesas Solutions Corporation
************************************************************************
* History		: 2011.05.04
*				: Ver 1.01
*				: Release CS3.
*""FILE COMMENT END""**************************************************/

#ifndef R_PDL_COMMON_DEFS_RX62Txx_H
#define R_PDL_COMMON_DEFS_RX62Txx_H

#include <stdint.h>
#include <stdbool.h>
#include <machine.h>
#include <stddef.h>
#include "iodefine_RPDL.h"

/* Callback function type */
typedef void (* VoidCallBackFunc)(void);

/* The supported MCU group */
#define PDL_MCU_GROUP RX62T

/* The highest interrupt priority level */
#define IPL_MAX	15

/* Use the I/O register area to indicate that a callback function pointer is not to be used */
#define PDL_NO_FUNC	(VoidCallBackFunc)0x00080000ul
/* Use the ROM area to indicate that a data pointer is not to be used */
#define PDL_NO_PTR (void *)0xFFFFFFFCul
/* When no parameters options are required */
#define PDL_NO_DATA 0

/* Shared global variables */
extern volatile uint32_t rpdl_CGC_f_pclk;
extern volatile uint32_t rpdl_CGC_f_iclk;
extern volatile	 uint8_t rpdl_INTC_brk_command;
extern volatile	 uint8_t rpdl_INTC_brk_data8;
extern volatile uint32_t rpdl_INTC_saved_isp;

/* BRK handler command options */
typedef enum {
	BRK_NO_COMMAND,
	BRK_START_ADC_10,
	BRK_START_ADC_10_AND_SLEEP,
	BRK_START_ADC_12,
	BRK_START_ADC_12_AND_SLEEP,
	BRK_SLEEP,
	BRK_ALL_MODULE_CLOCK_STOP,
	BRK_STANDBY,
	BRK_DEEP_STANDBY,
	BRK_LOAD_FINTV_REGISTER,
	BRK_WRITE_IPL,
	BRK_CMT_START,
	BRK_CMT_STOP
} brk_commands;

/* Bit definitions */
#define  BIT_0 0x00000001ul
#define  BIT_1 0x00000002ul
#define  BIT_2 0x00000004ul
#define  BIT_3 0x00000008ul
#define  BIT_4 0x00000010ul
#define  BIT_5 0x00000020ul
#define  BIT_6 0x00000040ul
#define  BIT_7 0x00000080ul
#define  BIT_8 0x00000100ul
#define  BIT_9 0x00000200ul
#define BIT_10 0x00000400ul
#define BIT_11 0x00000800ul
#define BIT_12 0x00001000ul
#define BIT_13 0x00002000ul
#define BIT_14 0x00004000ul
#define BIT_15 0x00008000ul
#define BIT_16 0x00010000ul
#define BIT_17 0x00020000ul
#define BIT_18 0x00040000ul
#define BIT_19 0x00080000ul
#define BIT_20 0x00100000ul
#define BIT_21 0x00200000ul
#define BIT_22 0x00400000ul
#define BIT_23 0x00800000ul
#define BIT_24 0x01000000ul
#define BIT_25 0x02000000ul
#define BIT_26 0x04000000ul
#define BIT_27 0x08000000ul
#define BIT_28 0x10000000ul
#define BIT_29 0x20000000ul
#define BIT_30 0x40000000ul
#define BIT_31 0x80000000ul

#define INV_BIT_0  0xFFFFFFFEul
#define INV_BIT_1  0xFFFFFFFDul
#define INV_BIT_2  0xFFFFFFFBul
#define INV_BIT_3  0xFFFFFFF7ul
#define INV_BIT_4  0xFFFFFFEFul
#define INV_BIT_5  0xFFFFFFDFul
#define INV_BIT_6  0xFFFFFFBFul
#define INV_BIT_7  0xFFFFFF7Ful
#define INV_BIT_8  0xFFFFFEFFul
#define INV_BIT_9  0xFFFFFDFFul
#define INV_BIT_10 0xFFFFFBFFul
#define INV_BIT_11 0xFFFFF7FFul
#define INV_BIT_12 0xFFFFEFFFul
#define INV_BIT_13 0xFFFFDFFFul
#define INV_BIT_14 0xFFFFBFFFul
#define INV_BIT_15 0xFFFF7FFFul
#define INV_BIT_16 0xFFFEFFFFul
#define INV_BIT_17 0xFFFDFFFFul
#define INV_BIT_18 0xFFFBFFFFul
#define INV_BIT_19 0xFFF7FFFFul
#define INV_BIT_20 0xFFEFFFFFul
#define INV_BIT_21 0xFFDFFFFFul
#define INV_BIT_22 0xFFBFFFFFul
#define INV_BIT_23 0xFF7FFFFFul
#define INV_BIT_24 0xFEFFFFFFul
#define INV_BIT_25 0xFDFFFFFFul
#define INV_BIT_26 0xFBFFFFFFul
#define INV_BIT_27 0xF7FFFFFFul
#define INV_BIT_28 0xEFFFFFFFul
#define INV_BIT_29 0xDFFFFFFFul
#define INV_BIT_30 0xBFFFFFFFul
#define INV_BIT_31 0x7FFFFFFFul

/* Interrupt vector numbers */
#define PDL_INTC_VECTOR_BUSERR		VECT_BSC_BUSERR
#define PDL_INTC_VECTOR_FIFERR		VECT_FCUIF_FIFERR
#define PDL_INTC_VECTOR_FRDYI		VECT_FCUIF_FRDYI
#define PDL_INTC_VECTOR_SWINT		VECT_ICU_SWINT
#define PDL_INTC_VECTOR_CMT0		VECT_CMT0_CMI0
#define PDL_INTC_VECTOR_CMT1		VECT_CMT1_CMI1
#define PDL_INTC_VECTOR_CMT2		VECT_CMT2_CMI2
#define PDL_INTC_VECTOR_CMT3		VECT_CMT3_CMI3
#define PDL_INTC_VECTOR_SPEI0		VECT_RSPI0_SPEI0
#define PDL_INTC_VECTOR_SPRI0		VECT_RSPI0_SPRI0
#define PDL_INTC_VECTOR_SPTI0		VECT_RSPI0_SPTI0
#define PDL_INTC_VECTOR_SPII0		VECT_RSPI0_SPII0
#define PDL_INTC_VECTOR_ERS0		VECT_CAN0_ERS0
#define PDL_INTC_VECTOR_RXF0		VECT_CAN0_RXF0
#define PDL_INTC_VECTOR_TXF0		VECT_CAN0_TXF0
#define PDL_INTC_VECTOR_RXM0		VECT_CAN0_RXM0
#define PDL_INTC_VECTOR_TXM0		VECT_CAN0_TXM0
#define PDL_INTC_VECTOR_IRQ0		VECT_ICU_IRQ0
#define PDL_INTC_VECTOR_IRQ1		VECT_ICU_IRQ1
#define PDL_INTC_VECTOR_IRQ2		VECT_ICU_IRQ2
#define PDL_INTC_VECTOR_IRQ3		VECT_ICU_IRQ3
#define PDL_INTC_VECTOR_IRQ4		VECT_ICU_IRQ4
#define PDL_INTC_VECTOR_IRQ5		VECT_ICU_IRQ5
#define PDL_INTC_VECTOR_IRQ6		VECT_ICU_IRQ6
#define PDL_INTC_VECTOR_IRQ7		VECT_ICU_IRQ7
#define PDL_INTC_VECTOR_WOVI		VECT_WDT_WOVI
#define PDL_INTC_VECTOR_ADI0		VECT_AD0_ADI0
#define PDL_INTC_VECTOR_S12ADI0		VECT_S12AD0_S12ADI0
#define PDL_INTC_VECTOR_S12ADI1		VECT_S12AD1_S12ADI1
#define PDL_INTC_VECTOR_CMPI		VECT_S12AD_CMPI
#define PDL_INTC_VECTOR_TGIA0		VECT_MTU0_TGIA0
#define PDL_INTC_VECTOR_TGIB0		VECT_MTU0_TGIB0
#define PDL_INTC_VECTOR_TGIC0		VECT_MTU0_TGIC0
#define PDL_INTC_VECTOR_TGID0		VECT_MTU0_TGID0
#define PDL_INTC_VECTOR_TCIV0		VECT_MTU0_TCIV0
#define PDL_INTC_VECTOR_TGIE0		VECT_MTU0_TGIE0
#define PDL_INTC_VECTOR_TGIF0		VECT_MTU0_TGIF0
#define PDL_INTC_VECTOR_TGIA1		VECT_MTU1_TGIA1
#define PDL_INTC_VECTOR_TGIB1		VECT_MTU1_TGIB1
#define PDL_INTC_VECTOR_TCIV1		VECT_MTU1_TCIV1
#define PDL_INTC_VECTOR_TCIU1		VECT_MTU1_TCIU1
#define PDL_INTC_VECTOR_TGIA2		VECT_MTU2_TGIA2
#define PDL_INTC_VECTOR_TGIB2		VECT_MTU2_TGIB2
#define PDL_INTC_VECTOR_TCIV2		VECT_MTU2_TCIV2
#define PDL_INTC_VECTOR_TCIU2		VECT_MTU2_TCIU2
#define PDL_INTC_VECTOR_TGIA3		VECT_MTU3_TGIA3
#define PDL_INTC_VECTOR_TGIB3		VECT_MTU3_TGIB3
#define PDL_INTC_VECTOR_TGIC3		VECT_MTU3_TGIC3
#define PDL_INTC_VECTOR_TGID3		VECT_MTU3_TGID3
#define PDL_INTC_VECTOR_TCIV3		VECT_MTU3_TCIV3
#define PDL_INTC_VECTOR_TGIA4		VECT_MTU4_TGIA4
#define PDL_INTC_VECTOR_TGIB4		VECT_MTU4_TGIB4
#define PDL_INTC_VECTOR_TGIC4		VECT_MTU4_TGIC4
#define PDL_INTC_VECTOR_TGID4		VECT_MTU4_TGID4
#define PDL_INTC_VECTOR_TCIV4		VECT_MTU4_TCIV4
#define PDL_INTC_VECTOR_TGIU5		VECT_MTU5_TGIU5
#define PDL_INTC_VECTOR_TGIV5		VECT_MTU5_TGIV5
#define PDL_INTC_VECTOR_TGIW5		VECT_MTU5_TGIW5
#define PDL_INTC_VECTOR_TGIA6		VECT_MTU6_TGIA6
#define PDL_INTC_VECTOR_TGIB6		VECT_MTU6_TGIB6
#define PDL_INTC_VECTOR_TGIC6		VECT_MTU6_TGIC6
#define PDL_INTC_VECTOR_TGID6		VECT_MTU6_TGID6
#define PDL_INTC_VECTOR_TCIV6		VECT_MTU6_TCIV6
#define PDL_INTC_VECTOR_TGIE6		VECT_MTU6_TGIE6
#define PDL_INTC_VECTOR_TGIF6		VECT_MTU6_TGIF6
#define PDL_INTC_VECTOR_TGIA7		VECT_MTU7_TGIA7
#define PDL_INTC_VECTOR_TGIB7		VECT_MTU7_TGIB7
#define PDL_INTC_VECTOR_TGIC7		VECT_MTU7_TGIC7
#define PDL_INTC_VECTOR_TGID7		VECT_MTU7_TGID7
#define PDL_INTC_VECTOR_TCIV7		VECT_MTU7_TCIV7
#define PDL_INTC_VECTOR_OEI1		VECT_POE_OEI1
#define PDL_INTC_VECTOR_OEI2		VECT_POE_OEI2
#define PDL_INTC_VECTOR_OEI3		VECT_POE_OEI3
#define PDL_INTC_VECTOR_OEI4		VECT_POE_OEI4
#define PDL_INTC_VECTOR_GTCIA0		VECT_GPT0_GTCIA0
#define PDL_INTC_VECTOR_GTCIB0		VECT_GPT0_GTCIB0
#define PDL_INTC_VECTOR_GTCIC0		VECT_GPT0_GTCIC0
#define PDL_INTC_VECTOR_GTCIE0		VECT_GPT0_GTCIE0
#define PDL_INTC_VECTOR_GTCIV0		VECT_GPT0_GTCIV0
#define PDL_INTC_VECTOR_LOCO1		VECT_GPT0_LOCO1
#define PDL_INTC_VECTOR_GTCIA1		VECT_GPT1_GTCIA1
#define PDL_INTC_VECTOR_GTCIB1		VECT_GPT1_GTCIB1
#define PDL_INTC_VECTOR_GTCIC1		VECT_GPT1_GTCIC1
#define PDL_INTC_VECTOR_GTCIE1		VECT_GPT1_GTCIE1
#define PDL_INTC_VECTOR_GTCIV1		VECT_GPT1_GTCIV1
#define PDL_INTC_VECTOR_GTCIA2		VECT_GPT2_GTCIA2
#define PDL_INTC_VECTOR_GTCIB2		VECT_GPT2_GTCIB2
#define PDL_INTC_VECTOR_GTCIC2		VECT_GPT2_GTCIC2
#define PDL_INTC_VECTOR_GTCIE2		VECT_GPT2_GTCIE2
#define PDL_INTC_VECTOR_GTCIV2		VECT_GPT2_GTCIV2
#define PDL_INTC_VECTOR_GTCIA3		VECT_GPT3_GTCIA3
#define PDL_INTC_VECTOR_GTCIB3		VECT_GPT3_GTCIB3
#define PDL_INTC_VECTOR_GTCIC3		VECT_GPT3_GTCIC3
#define PDL_INTC_VECTOR_GTCIE3		VECT_GPT3_GTCIE3
#define PDL_INTC_VECTOR_GTCIV3		VECT_GPT3_GTCIV3
#define PDL_INTC_VECTOR_ERI0		VECT_SCI0_ERI0
#define PDL_INTC_VECTOR_RXI0		VECT_SCI0_RXI0
#define PDL_INTC_VECTOR_TXI0		VECT_SCI0_TXI0
#define PDL_INTC_VECTOR_TEI0		VECT_SCI0_TEI0
#define PDL_INTC_VECTOR_ERI1		VECT_SCI1_ERI1
#define PDL_INTC_VECTOR_RXI1		VECT_SCI1_RXI1
#define PDL_INTC_VECTOR_TXI1		VECT_SCI1_TXI1
#define PDL_INTC_VECTOR_TEI1		VECT_SCI1_TEI1
#define PDL_INTC_VECTOR_ERI2		VECT_SCI2_ERI2
#define PDL_INTC_VECTOR_RXI2		VECT_SCI2_RXI2
#define PDL_INTC_VECTOR_TXI2		VECT_SCI2_TXI2
#define PDL_INTC_VECTOR_TEI2		VECT_SCI2_TEI2
#define PDL_INTC_VECTOR_ICEEI0		VECT_RIIC0_ICEEI0
#define PDL_INTC_VECTOR_ICRXI0		VECT_RIIC0_ICRXI0
#define PDL_INTC_VECTOR_ICTXI0		VECT_RIIC0_ICTXI0
#define PDL_INTC_VECTOR_ICTEI0		VECT_RIIC0_ICTEI0
#define PDL_INTC_VECTOR_LIN0		VECT_LIN0_LIN0

#endif

/* End of file */
