/***********************************************************************/
/*                                                                     */
/*  FILE        :GimbalController.c                                    */
/*  DATE        :Thu, May 30, 2019                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#include "Delay.h"
#include "I2C.h"
#include "UART.h"
#include "PWM.h"
#include "MPU6050.h"
#include "PID.h"
#include "LED.h"

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

float PRY[3] = {0.0};
float theta_Pitch = 0;
float theta_Roll = 0;
float deviation_Pitch = 0;
float deviation_Roll = 0;
int DMPReady_flag = 0;
int LOG_flag = 0;
int ADC_flag = 0;
int Stop_flag = 0;
int btn_count = 0;
int btn_time_flag = 0;
int JoyStick_X = 0;
int JoyStick_Y = 0;
volatile unsigned int ADC_Result = 0;

void main(void);
#ifdef __cplusplus
extern "C"
{
    void abort(void);
}
#endif

void main(void)
{
    R_PG_Clock_Set();

    InitialLED();
    InitialI2C();
    InitialUART();

    //Initialze ADC Stuffs
    R_PG_ADC_12_Set();
    R_PG_ADC_12_Set_S12ADA0();
    R_PG_ADC_12_Set_S12ADA1();

    SetLED1(1); //Power-On

    SetLED4(1);    
    R_PG_ADC_12_StartConversionSW_S12ADA0();
    while(!ADC_flag);
    ADC_flag = 0;
    if(ADC_Result>3900){
        Stop_flag = 1;
        run_self_test_flag = 0;
    }else if(ADC_Result<200){
        Stop_flag = 0;
        run_self_test_flag = 0;
    }else{
        Stop_flag = 0;
        run_self_test_flag = 1;
    }
    
    while (Stop_flag);
    SetLED4(0);
    DMP_Init();
    SetLED2(1); //Initialized

    InitialPWMs();
    EnablePWM_A();
    EnablePWM_B();

    PID_Initial(&pid_Pitch);
    PID_Initial(&pid_Roll);
    pid_Pitch.Kp = 0.007; //0.02 0.025 1,0.008 0.03 1.1, 0.007 0.04 1.1
    pid_Pitch.Ki = 0.04;
    pid_Pitch.Kd = 1.1;
    pid_Pitch.UpperLimit = 0.5;
    pid_Pitch.LowerLimit = -0.5;
    pid_Roll.Kp = 0.25; //0.6 0.05 5.0,0.5 0.08 5.2, 0.6 0.06 5.3, 0.55 0.09 5.5
    pid_Roll.Ki = 0.07;
    pid_Roll.Kd = 5;
    pid_Roll.UpperLimit = 0.5;
    pid_Roll.LowerLimit = -0.5;
    LOG("Start While Loop.....\r\n");

    R_PG_ExtInterrupt_Set_IRQ0(); //Enable DMP interrupt
    R_PG_ExtInterrupt_Set_IRQ1();
    R_PG_ADC_12_StartConversionSW_S12ADA1();
    while (1)
    {

        if(btn_time_flag){
            btn_time_flag = 0;
            switch(btn_count){
                case 1:
                    deviation_Pitch = 0;
                    deviation_Roll = 0;
                    break;
                case 2:
                    SetLED3(1);
                    break;
            }
            btn_count = 0;
        }
        if (ADC_flag)
        {
            ADC_flag = 0;
            JoyStick_X = ADC_Result & 0x1FFF;
            JoyStick_Y = (ADC_Result >> 16) & 0x1FFF;

            if (JoyStick_X > 2500)
            {
                if (deviation_Pitch < 80)
                    deviation_Pitch += (JoyStick_X - 2500) * 0.0000004;
            }
            else if (JoyStick_X < 1600)
            {
                if (deviation_Pitch > -80)
                    deviation_Pitch += (JoyStick_X - 1600) * 0.0000004;
            }

            if (JoyStick_Y > 2500)
            {
                if (deviation_Roll < 45)
                    deviation_Roll += (JoyStick_Y - 2500) * 0.0000002;
            }
            else if (JoyStick_Y < 1600)
            {
                if (deviation_Roll > -45)
                    deviation_Roll += (JoyStick_Y - 1600) * 0.0000002;
            }
        }

        if (DMPReady_flag)
        {
            DMPReady_flag = 0;
            if (Read_DMP(&PRY[0], &PRY[1], &PRY[2]) == 0)
            {

                if ((PRY[1] < 0) && (PRY[1] >= -180))
                {
                    PRY[1] += 180;
                }
                else
                {
                    PRY[1] -= 180;
                }

                pid_Pitch.ActualValue = PRY[1];
                theta_Pitch += PID_Increase_Pitch(90 + deviation_Pitch);
                calcPWM_A_Sine(theta_Pitch);

                pid_Roll.ActualValue = PRY[0];
                theta_Roll += PID_Increase_Roll(deviation_Roll);
                calcPWM_B_Sine(theta_Roll);

                if (LOG_flag)
                    LOG("CP:%f,MP:%f,CR:%f,MR:%f\r\n", PRY[1], theta_Pitch, PRY[0], theta_Roll);

                LOG_flag ^= 1;
            }
        }

        if (Stop_flag)
        {
            DisablePWM_A();
            DisablePWM_B();
        }
        else
        {
            EnablePWM_A();
            EnablePWM_B();
        }
    }
}

void Irq0IntFunc(void)
{
    DMPReady_flag = 1;
}

void Irq1IntFunc(void)
{
    if(btn_count==0){
        R_PG_Timer_Start_CMT_U0_C1();
    }
    btn_count ++;    
}

void Cmt1IntFunc(void){
    R_PG_Timer_HaltCount_CMT_U0_C1();
    btn_time_flag = 1;
}

void S12ad0IntFunc(void)
{
    R_PG_ADC_12_GetResult_S12ADA0(&ADC_Result);
    ADC_flag = 1;
}

void S12ad1IntFunc(void)
{
    R_PG_ADC_12_GetResult_S12ADA1(&ADC_Result);
    ADC_flag = 1;
}

#ifdef __cplusplus
void abort(void)
{
}
#endif
